#!/usr/bin/env python3

import argparse
import os
import subprocess
import sys


if __name__ == "__main__":
    
    parser = argparse.ArgumentParser(description="create a Wagtail site")
    parser.epilog = "Creates a Wagtail site, migrates, inserts superuser. External databases require a database with the same name as the site???"


    parser.add_argument(
        '--site-location',
        type=str,
        default="/srv",
        help="used to position the site codebase",
        )

    parser.add_argument(
        '--site-name',
        type=str,
        help="used in directory names and site admin",
        )
        
    parser.add_argument(
        '--admin-user',
        type=str,
        help="for Wagtail site admin')",
        )

    parser.add_argument(
        '--admin-password',
        type=str,
        help="for Wagtail site admin",
        )

    parser.add_argument(
        '--admin-email',
        type=str,
        help="for Wagtail site admin",
        )
        
        
    # Only parse for known args, then ditch unknown argument tuple.
    # In use accepts other arguments, matching prefixes,
    # but we can ignore them.
    args = parser.parse_known_args()
    args = args[0]

    
    # Missing details
    argIsNone = [k for k,v in vars(args).items() if not v ]
    if (len(argIsNone) > 0):
        print ("Information needed: {}".format(", ".join(argIsNone)))
    
    # Ensure necessary details
    if not args.site_name: 
        args.site_name = input("New site, no name?\n> ")
    if not args.admin_user: 
        args.admin_user = input("Site admin user most helpful\n> ")
    if not args.admin_password: 
        args.admin_password = input("Oh, you need a site admin password, you must!\n> ")
    if not args.admin_email: 
        args.admin_email = input("Admin email much loved by Django\n> ")


    subprocess.call([
        "createscaffold.sh",
        args.site_location, 
        args.site_name,
        "wagtail"
        ])

    subprocess.call([
        "migratesite.sh",
        args.site_location, 
        args.site_name
        ])
        
    subprocess.call([
        "createsuperuser.sh",
        args.site_location, 
        args.site_name, 
        args.admin_user, 
        args.admin_password, 
        args.admin_email,
        ])
