#!/usr/bin/env python3

import argparse
import os


if __name__ == "__main__":
    
    parser = argparse.ArgumentParser(description="list Django/Wagtail sites")

    parser.add_argument(
        '--site-location',
        type=str,
        default="/srv",
        help="used to position the site codebase",
        )

    # Only parse for known args, then ditch unknown argument tuple.
    # In use accepts other arguments, matching prefixes,
    # but we can ignore them.
    args = parser.parse_known_args()
    args = args[0]
    
site_pos = args.site_location
    
fileList = [fn for fn in os.listdir(args.site_location) if os.path.isdir(os.path.join(site_pos, fn)) and os.path.isfile(os.path.join(site_pos, fn, 'manage.py'))]
for filename in fileList:
    print(filename)
if len(fileList) == 0:
    print("No Django or Wagtail installations appear")
else:
    print("(probably)")
